import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

import Contents from '../components/pages/main';
import { NAME } from '../static/me';

type StaticProps = { indicators: Indicator[] };

const Home: NextPage<StaticProps> = ({ indicators }) => (
  <>
    <Head>
      <title>{NAME} portfolio</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.png' />
    </Head>
    <Contents indicators={indicators} />
  </>
);

export default Home;

export const getStaticProps: GetStaticProps<StaticProps> = async (context) => {
  if (!process.env.GAS_END_POINT) {
    return {
      props: { indicators: [] },
    };
  }

  const response = await fetch(process.env.GAS_END_POINT);

  const data = await response.json();

  const indicators: Indicator[] = [
    { number: data?.numUsers || 0, unit: 'companies' },
    { number: data?.counter || 0, unit: 'actions' },
  ];

  return {
    props: { indicators },
    revalidate: 600,
  };
};
